#!/bin/bash

make kernel-install

jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
#jupyter nbextension enable agda-extension/main
#jupyter nbextension enable literate-markdown/main
jupyter nbextension enable toc2/main
#jupyter nbextension enable hide_input/main
#jupyter nbextension enable init_cell/main
#jupyter nbextension enable freeze/main

# change theme with jupyter-themes
jt -t grade3 -f roboto -fs 10 -cellw 800 -altp -T