#!/bin/bash

make kernel-install

jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
#jupyter nbextension enable agda-extension/main
#jupyter nbextension enable literate-markdown/main
jupyter nbextension enable toc2/main
#jupyter nbextension enable hide_input/main
#jupyter nbextension enable init_cell/main
#jupyter nbextension enable freeze/main

jupyter labextension install @jupyterlab/geojson-extension jupyterlab-drawio
jupyter serverextension enable --py jupyterlab --sys-prefix

# change theme with jupyter-themes
jt -t grade3 -f roboto -fs 10 -cellw 800 -altp -T

add-apt-repository ppa:swi-prolog/stable
apt-get update
apt-get install swi-prolog
